### ISSUE TITLE
Error trying to reach INIS

### ISSUE THREAD

**Issue by WolfofGovt** [Feko/ireland-immigration-appointment-finder-inis#1]
Hi there Feko, thank you for such project, it is sth necessary I believe. 

While I try to run the code on W10 (Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32., I get an error. Do you have any idea to solve this?

Thank you,

←[95m[2021-07-23 14:32:55] - ←[0mLooking for appointment slots...
←[95m[2021-07-23 14:32:56] - ←[0m←[91mERROR trying to reach INIS.
←[95m[2021-07-23 14:32:56] - ←[0mWaiting for 10 seconds
←[95m[2021-07-23 14:33:06] - ←[0mLooking for appointment slots...
←[95m[2021-07-23 14:33:06] - ←[0m←[91mERROR trying to reach INIS.

**Comment by Feko** [comment]
Hey, @WolfofGovt thanks for letting me know! :)
Indeed I can reproduce the error locally. It seems some sort of javascript redirection layer was added on the main page, and we can no longer scrap it for the tokens.
I'll try to overcome it on the weekend, if I fail, my plan B is to use Selenium WebDriver to access the site, allow the redirection to take place, and then fetch the tokens.
Keep you updated.

**Comment by Feko** [comment]
Hey @WolfofGovt thanks again for your issue. I found another bug while fixing this, and managed to make it work again.
The government added a **F5 Big-IP Web Scrapping Protection** layer in front of the main website. 

While the idea of having a Government IT section concerned with the issues and working toward solving the problem is an amazing thing, this approach is ineffective. There are many ways to overcome this protection, such as automating a browser with **Selenium**, or using tools such as **Scrapping Hub's Splash.** I choose to use **PhantomJS,** which you need to install and set your computer **PATH** environment variable to reach your downloaded PhantomJS.

I really wish the government would hire high skilled people to have this problem fixed **for good**, in code-level, instead of paying hundreds of thousands in ineffective software licenses.

Anyway, it's working now. There's this new dependency that needs to be installed (PhantomJS - there's some useful links on https://github.com/Feko/ireland-immigration-appointment-finder-inis/#installation), and you need to grab the latest version of the code. I could only test it on my personal computer, which runs **Manjaro Linux.** It seems you are using **Windows,** tomorrow I should be able to test it on Windows too.

![image](https://user-images.githubusercontent.com/2065159/126896677-f25df45b-fa87-4e16-b535-078e80491552.png)

Let me know if you need some help setting it up.

Stay safe!

**Comment by WolfofGovt** [comment]
Thank you @Feko , now it works! It is really weird that government does not fix this for good. For anyone who could not download phantomjs you may use the below link:
https://repo1.maven.org/maven2/com/github/klieber/phantomjs/2.1.1/

And for environment setting you can follow here:
https://www.tutorialspoint.com/phantomjs/phantomjs_environment_setup.htm

And for Windows here maybe:
https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/

Thank you very much again for your quick response!

Best,

**Comment by lauraarossi** [comment]
Getting the same error even with latest build/phantomjs: 

←[95m[2021-10-29 15:30:03] - ←[0mLooking for appointment slots...
←[95m[2021-10-29 15:30:03] - ←[0m←[91mERROR trying to reach INIS.
←[95m[2021-10-29 15:30:03] - ←[0mWaiting for 10 seconds

**Comment by Feko** [comment]
Hi @lauraarossi sorry for the late response, I was on holiday :)
Sorry to hear you are having issues with the tool. I just tried to run it, and it seems to be working fine:
```
2021-11-07 07:05:18] - Looking for appointment slots...
[2021-11-07 07:05:24] - No appointments available.
{
    "empty": "TRUE"
}
[2021-11-07 07:05:24] - Waiting for 10 seconds
[2021-11-07 07:05:34] - Looking for appointment slots...
[2021-11-07 07:05:40] - No appointments available.
{
    "empty": "TRUE"
}
[2021-11-07 07:05:40] - Waiting for 10 seconds
```

Could you please try again? Also, try changing `DEBUG = False` to `DEBUG = True` in the file `constants.py` for a better (yet verbose) error message.
If it persists, please let me know, I'd like to understand your scenario a little bit more.

Cheers.
